<?php

namespace Salim\PlateformeBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getApplicationsWithAdvert ($limit)
	{

		return $this 
		-> createQueryBuilder('app')
		-> innerJoin('app.advert','a')
		-> addSelect('a')
		-> setMaxResults($limit)
		-> getQuery()
		-> getResult()
		;

	}

}
