<?php

namespace Proxies\__CG__\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entreprise extends \UserBundle\Entity\Entreprise implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'user', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'siret', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'salaries', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'abonnements', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'nbAbo', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'nbSal', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'adresse', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'responsable', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'telephone', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'site'];
        }

        return ['__isInitialized__', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'id', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'user', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'siret', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'salaries', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'abonnements', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'nbAbo', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'nbSal', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'adresse', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'responsable', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'telephone', '' . "\0" . 'UserBundle\\Entity\\Entreprise' . "\0" . 'site'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entreprise $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiret($siret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiret', [$siret]);

        return parent::setSiret($siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiret', []);

        return parent::getSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbAbo($nbAbo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbAbo', [$nbAbo]);

        return parent::setNbAbo($nbAbo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbAbo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbAbo', []);

        return parent::getNbAbo();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable($responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', [$site]);

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', []);

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addSalary(\UserBundle\Entity\Salarie $salary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSalary', [$salary]);

        return parent::addSalary($salary);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSalary(\UserBundle\Entity\Salarie $salary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSalary', [$salary]);

        return parent::removeSalary($salary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalaries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalaries', []);

        return parent::getSalaries();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbonnement(\ConciergerieBundle\Entity\Abonnement $abonnement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbonnement', [$abonnement]);

        return parent::addAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbonnement(\ConciergerieBundle\Entity\Abonnement $abonnement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbonnement', [$abonnement]);

        return parent::removeAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbonnements()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbonnements', []);

        return parent::getAbonnements();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(\UserBundle\Entity\Adresse $adresse = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSal($nbSal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSal', [$nbSal]);

        return parent::setNbSal($nbSal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSal', []);

        return parent::getNbSal();
    }

}
