oc_platform_home:
    path: /{page}
    defaults: 
      _controller: SalimPlateformeBundle:Advert:index
      page: 1
    requirements: 
      page: \d*

oc_platform_view:
    path: /advert/{id}
    defaults: 
      _controller: SalimPlateformeBundle:Advert:view
    requirements:
      page: \d+

oc_platform_add:
    path: /add
    defaults: 
      _controller: SalimPlateformeBundle:Advert:add

oc_platform_edit:
    path: /edit/{id}
    defaults:
      _controller: SalimPlateformeBundle:Advert:edit
    requirements:
      id: \d+

oc_platform_delete:
    path: /delete/{id}
    defaults: 
      _controller: SalimPlateformeBundle:Advert:delete
    requirements:
      page: \d+